### ISSUE TITLE
Archlinux can't launch

### ISSUE THREAD

**Issue by uratom962** [xmikos/qopenvpn#7]
Hi I can't launch your client software gui : 
`$ qopenvpn 
Traceback (most recent call last):
  File "/usr/bin/qopenvpn", line 33, in <module>
    sys.exit(load_entry_point('QOpenVPN==2.0.0', 'gui_scripts', 'qopenvpn')())
  File "/usr/bin/qopenvpn", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: QOpenVPN
`

**Comment by trougnouf** [comment]
It launches here but nothing meaningful happens. I get an icon in the sway status bar, double clicking on it prompts for my password in the terminal, and entering my password yields `Failed to start None@None.service: Unit None@None.service not found.`

**Comment by kalka11** [comment]
> It launches here but nothing meaningful happens. I get an icon in the sway status bar, double clicking on it prompts for my password in the terminal, and entering my password yields `Failed to start None@None.service: Unit None@None.service not found.`

yes i have the same problem

**Comment by JiriPodhorny** [comment]
It can't read config files from /etc/openvpn/client (folder is not accesible for normal user)
If you run sudo qopenvpn, it connects ...

**Comment by techtycho** [comment]
Thanks

**Comment by DIMFLIX** [comment]
> It can't read config files from /etc/openvpn/client (folder is not accesible for normal user) If you run sudo qopenvpn, it connects ...

I tried using sudo - nothing worked. The error is the same
